export class SvgToPatEngine {
  static async fetchAndConvert(svgUrl, name = 'PATTERN') {
    try {
      const response = await fetch(svgUrl);
      const svgText = await response.text();
      return this.convertSvgToPat(svgText, name);
    } catch (e) {
      console.error("Error converting SVG to PAT:", e);
      throw e;
    }
  }

  static convertSvgToPat(svgText, patternName) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgText, "image/svg+xml");
    const svgEl = doc.querySelector('svg');

    let w = 100, h = 100;
    if (svgEl.getAttribute('viewBox')) {
      const vb = svgEl.getAttribute('viewBox').split(/[ ,]+/);
      w = parseFloat(vb[2]);
      h = parseFloat(vb[3]);
    } else if (svgEl.getAttribute('width') && svgEl.getAttribute('height')) {
      w = parseFloat(svgEl.getAttribute('width'));
      h = parseFloat(svgEl.getAttribute('height'));
    }

    const segments = [];

    // Extract <line>
    doc.querySelectorAll('line').forEach(el => {
      segments.push({
        x1: parseFloat(el.getAttribute('x1')),
        y1: parseFloat(el.getAttribute('y1')),
        x2: parseFloat(el.getAttribute('x2')),
        y2: parseFloat(el.getAttribute('y2'))
      });
    });

    // Extract <rect>
    doc.querySelectorAll('rect').forEach(el => {
      const x = parseFloat(el.getAttribute('x') || 0);
      const y = parseFloat(el.getAttribute('y') || 0);
      const width = parseFloat(el.getAttribute('width'));
      const height = parseFloat(el.getAttribute('height'));
      segments.push({ x1: x, y1: y, x2: x + width, y2: y });
      segments.push({ x1: x + width, y1: y, x2: x + width, y2: y + height });
      segments.push({ x1: x + width, y1: y + height, x2: x, y2: y + height });
      segments.push({ x1: x, y1: y + height, x2: x, y2: y });
    });

    // Extract <path> (Only M, L, H, V, Z)
    doc.querySelectorAll('path').forEach(el => {
      const d = el.getAttribute('d');
      if (/[CcSsQqTtAa]/.test(d)) return; // Skip curves
      
      const commands = d.match(/[a-zA-Z][^a-zA-Z]*/g);
      if (!commands) return;

      let startX = 0, startY = 0;
      let curX = 0, curY = 0;

      commands.forEach(cmdStr => {
        const cmd = cmdStr[0];
        const args = cmdStr.slice(1).trim().split(/[ ,\n\r]+/).map(parseFloat).filter(n => !isNaN(n));
        
        switch (cmd) {
          case 'M':
            curX = args[0]; curY = args[1];
            startX = curX; startY = curY;
            for (let i = 2; i < args.length; i += 2) {
              segments.push({ x1: curX, y1: curY, x2: args[i], y2: args[i+1] });
              curX = args[i]; curY = args[i+1];
            }
            break;
          case 'm':
            curX += args[0]; curY += args[1];
            startX = curX; startY = curY;
            for (let i = 2; i < args.length; i += 2) {
              segments.push({ x1: curX, y1: curY, x2: curX + args[i], y2: curY + args[i+1] });
              curX += args[i]; curY += args[i+1];
            }
            break;
          case 'L':
            for (let i = 0; i < args.length; i += 2) {
              segments.push({ x1: curX, y1: curY, x2: args[i], y2: args[i+1] });
              curX = args[i]; curY = args[i+1];
            }
            break;
          case 'l':
            for (let i = 0; i < args.length; i += 2) {
              segments.push({ x1: curX, y1: curY, x2: curX + args[i], y2: curY + args[i+1] });
              curX += args[i]; curY += args[i+1];
            }
            break;
          case 'H':
            for (let i = 0; i < args.length; i++) {
              segments.push({ x1: curX, y1: curY, x2: args[i], y2: curY });
              curX = args[i];
            }
            break;
          case 'h':
            for (let i = 0; i < args.length; i++) {
              segments.push({ x1: curX, y1: curY, x2: curX + args[i], y2: curY });
              curX += args[i];
            }
            break;
          case 'V':
            for (let i = 0; i < args.length; i++) {
              segments.push({ x1: curX, y1: curY, x2: curX, y2: args[i] });
              curY = args[i];
            }
            break;
          case 'v':
            for (let i = 0; i < args.length; i++) {
              segments.push({ x1: curX, y1: curY, x2: curX, y2: curY + args[i] });
              curY += args[i];
            }
            break;
          case 'Z':
          case 'z':
            segments.push({ x1: curX, y1: curY, x2: startX, y2: startY });
            curX = startX; curY = startY;
            break;
        }
      });
    });

    return this.generatePat(segments, w, h, patternName);
  }

  static round(val, decimals = 5) {
    return Number(Math.round(val + 'e' + decimals) + 'e-' + decimals);
  }

  static generatePat(segments, w, h, patternName) {
    let patLines = [`*${patternName}, Generated by LispCentral`];
    
    // Group horizontal and vertical collinear lines for optimization
    const horizontals = {};
    const verticals = {};
    const others = [];

    segments.forEach(seg => {
      let x1 = this.round(seg.x1); let y1 = this.round(seg.y1);
      let x2 = this.round(seg.x2); let y2 = this.round(seg.y2);

      // SVG y is down, PAT y is up. Invert Y coordinate.
      y1 = -y1; y2 = -y2;

      if (y1 === y2) {
        if (x1 > x2) { let t = x1; x1 = x2; x2 = t; }
        if (!horizontals[y1]) horizontals[y1] = [];
        horizontals[y1].push({ min: x1, max: x2 });
      } else if (x1 === x2) {
        if (y1 > y2) { let t = y1; y1 = y2; y2 = t; }
        if (!verticals[x1]) verticals[x1] = [];
        verticals[x1].push({ min: y1, max: y2 });
      } else {
        others.push({ x1, y1, x2, y2 });
      }
    });

    // Merge collinear and emit PAT
    
    // Horizontals: angle = 0, deltaX = 0, deltaY = h
    Object.keys(horizontals).forEach(yStr => {
      let y = parseFloat(yStr);
      let segs = horizontals[yStr].sort((a, b) => a.min - b.min);
      // Merge overlapping
      let merged = [segs[0]];
      for (let i = 1; i < segs.length; i++) {
        let last = merged[merged.length - 1];
        if (segs[i].min <= last.max + 0.001) {
          last.max = Math.max(last.max, segs[i].max);
        } else {
          merged.push(segs[i]);
        }
      }
      
      // If the merged segments cover exactly [0, w], it's a solid line.
      // Or if there's offset wrap-around: e.g. [0, 30] and [70, 100], width=100.
      if (merged.length > 1 && merged[0].min === 0 && merged[merged.length - 1].max === w) {
        merged[0].min = -(w - merged[merged.length - 1].min);
        merged.pop();
      }

      merged.forEach(seg => {
        let length = seg.max - seg.min;
        if (length <= 0) return;
        if (length >= w - 0.001) {
          // Continuous line
          patLines.push(`0, 0,${this.round(y)}, 0,${this.round(h)}`);
        } else {
          let space = -(w - length);
          patLines.push(`0, ${this.round(seg.min)},${this.round(y)}, 0,${this.round(h)}, ${this.round(length)}, ${this.round(space)}`);
        }
      });
    });

    // Verticals: angle = 90, deltaX = 0, deltaY = w
    Object.keys(verticals).forEach(xStr => {
      let x = parseFloat(xStr);
      let segs = verticals[xStr].sort((a, b) => a.min - b.min);
      let merged = [segs[0]];
      for (let i = 1; i < segs.length; i++) {
        let last = merged[merged.length - 1];
        if (segs[i].min <= last.max + 0.001) {
          last.max = Math.max(last.max, segs[i].max);
        } else {
          merged.push(segs[i]);
        }
      }
      
      if (merged.length > 1 && merged[0].min === -h && merged[merged.length - 1].max === 0) {
        merged[0].min = -(h - merged[merged.length - 1].min) - h; // Wrapped
        merged.pop();
      }

      merged.forEach(seg => {
        let length = seg.max - seg.min;
        if (length <= 0) return;
        if (length >= h - 0.001) {
          patLines.push(`90, ${this.round(x)},0, 0,${this.round(w)}`);
        } else {
          let space = -(h - length);
          patLines.push(`90, ${this.round(x)},${this.round(seg.min)}, 0,${this.round(w)}, ${this.round(length)}, ${this.round(space)}`);
        }
      });
    });

    // Others (diagonals, unmerged)
    others.forEach(seg => {
      let dx = seg.x2 - seg.x1;
      let dy = seg.y2 - seg.y1;
      let angle = Math.atan2(dy, dx) * (180 / Math.PI);
      if (angle < 0) angle += 360;
      
      let length = Math.sqrt(dx*dx + dy*dy);
      // For random diagonals, generating perfect repeat deltas is hard without semantic info.
      // As a fallback, we define a solid line, but the repeat delta will just use bounding box dimensions. 
      // This is a naive translation for diagonals and might look overlapping if not perfectly structured.
      patLines.push(`${this.round(angle)}, ${this.round(seg.x1)},${this.round(seg.y1)}, ${this.round(w)},${this.round(h)}, ${this.round(length)}, -${this.round(Math.max(w,h) * 2)}`);
    });

    return patLines.join('\n');
  }
}
